import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, differenceInMinutes, startOfMonth, endOfMonth } from 'date-fns';
import type { Trip, Expense, EvidenceItem, VisitSession } from '../types';
import { storage } from './storage';

export class ReportGenerator {
    private static createHeader(doc: jsPDF, title: string, parentName: string) {
        const pageWidth = doc.internal.pageSize.width;

        // Title
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text(title, pageWidth / 2, 20, { align: 'center' });

        // Subtitle / Date
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated on: ${format(new Date(), 'PPP p')}`, pageWidth / 2, 28, { align: 'center' });

        // Parent Info
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);
        doc.text(`Parent: ${parentName}`, 14, 40);

        // Line separator
        doc.setDrawColor(200, 200, 200);
        doc.line(14, 45, pageWidth - 14, 45);
    }

    private static addFooter(doc: jsPDF) {
        const pageCount = doc.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(
                `Page ${i} of ${pageCount} - Generated by DadTime App`,
                doc.internal.pageSize.width / 2,
                doc.internal.pageSize.height - 10,
                { align: 'center' }
            );
        }
    }

    static generateMileageReport(trips: Trip[], parentName: string) {
        const doc = new jsPDF();
        this.createHeader(doc, 'Mileage Log', parentName);

        const tableData = trips.map(trip => [
            format(new Date(trip.startTime), 'PP'),
            trip.purpose,
            trip.startLocation?.label || 'N/A',
            trip.endLocation?.label || 'N/A',
            `${trip.distanceMiles} mi`
        ]);

        autoTable(doc, {
            startY: 50,
            head: [['Date', 'Purpose', 'Start', 'End', 'Distance']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229] }, // Indigo-600
        });

        const totalMiles = trips.reduce((sum, t) => sum + (t.distanceMiles || 0), 0);

        const finalY = (doc as any).lastAutoTable.finalY + 10;
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Miles: ${totalMiles.toFixed(1)}`, 14, finalY);

        this.addFooter(doc);
        doc.save(`mileage_report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    }

    static generateExpenseReport(expenses: Expense[], parentName: string) {
        const doc = new jsPDF();
        this.createHeader(doc, 'Expense Report', parentName);

        const tableData = expenses.map(exp => [
            format(new Date(exp.date), 'PP'),
            exp.category,
            exp.merchantName || 'N/A',
            `$${exp.amount.toFixed(2)}`,
            exp.reimbursementStatus.replace('_', ' ')
        ]);

        autoTable(doc, {
            startY: 50,
            head: [['Date', 'Category', 'Merchant', 'Amount', 'Status']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [16, 185, 129] }, // Emerald-500
        });

        const totalAmount = expenses.reduce((sum, e) => sum + e.amount, 0);

        const finalY = (doc as any).lastAutoTable.finalY + 10;
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Expenses: $${totalAmount.toFixed(2)}`, 14, finalY);

        this.addFooter(doc);
        doc.save(`expense_report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    }

    static generateEvidenceReport(evidence: EvidenceItem[], parentName: string) {
        const doc = new jsPDF();
        this.createHeader(doc, 'Evidence Archive Log', parentName);

        const tableData = evidence.map(item => [
            format(new Date(item.importedAt), 'PP p'),
            item.type,
            item.notes || 'No notes'
        ]);

        autoTable(doc, {
            startY: 50,
            head: [['Date/Time', 'Type', 'Notes']],
            body: tableData,
            theme: 'grid',
            headStyles: { fillColor: [244, 63, 94] }, // Rose-500
            columnStyles: {
                2: { cellWidth: 'auto' } // Allow notes to wrap
            }
        });

        this.addFooter(doc);
        doc.save(`evidence_log_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    }

    static generateTimeShareReport(parentName: string) {
        const doc = new jsPDF();
        this.createHeader(doc, 'Time Share Report', parentName);

        // Get visits from storage
        const visits = storage.get<VisitSession>('visits');
        const completedVisits = visits.filter(v => v.endTime);

        // Calculate current month stats
        const now = new Date();
        const monthStart = startOfMonth(now);
        const monthEnd = endOfMonth(now);

        const thisMonthVisits = completedVisits.filter(v => {
            const startDate = new Date(v.startTime);
            return startDate >= monthStart && startDate <= monthEnd;
        });

        // Calculate hours by type
        const hoursByType: Record<string, number> = {};
        let totalHours = 0;
        let overnightCount = 0;
        let physicalCareCount = 0;

        thisMonthVisits.forEach(v => {
            const hours = differenceInMinutes(new Date(v.endTime!), new Date(v.startTime)) / 60;
            hoursByType[v.type] = (hoursByType[v.type] || 0) + hours;
            totalHours += hours;

            if (v.type === 'overnight') overnightCount++;
            if (v.type === 'physical_care') physicalCareCount++;
        });

        // Display summary stats
        let yPos = 60;
        doc.setFontSize(14);
        doc.setTextColor(40, 40, 40);
        doc.text(`Report Period: ${format(monthStart, 'MMMM yyyy')}`, 14, yPos);

        yPos += 15;
        doc.setFontSize(12);
        doc.text(`Total Visit Hours: ${totalHours.toFixed(1)} hours`, 14, yPos);
        yPos += 8;
        doc.text(`Overnight Visits: ${overnightCount}`, 14, yPos);
        yPos += 8;
        doc.text(`Physical Care Visits: ${physicalCareCount}`, 14, yPos);
        yPos += 8;
        doc.text(`Total Visits Logged: ${thisMonthVisits.length}`, 14, yPos);

        yPos += 15;

        // Table of visits
        const tableData = thisMonthVisits.map(v => {
            const hours = differenceInMinutes(new Date(v.endTime!), new Date(v.startTime)) / 60;
            return [
                format(new Date(v.startTime), 'PP'),
                format(new Date(v.startTime), 'p'),
                format(new Date(v.endTime!), 'p'),
                v.type.replace(/_/g, ' '),
                `${hours.toFixed(1)} hrs`
            ];
        });

        autoTable(doc, {
            startY: yPos,
            head: [['Date', 'Start', 'End', 'Type', 'Duration']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [26, 102, 255] },
        });

        // Time percentage calculation (assuming 720 hours per month)
        const monthlyHours = 730; // ~30 days * 24 hours
        const timeSharePercentage = (totalHours / monthlyHours) * 100;

        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(13);
        doc.setTextColor(26, 102, 255);
        doc.text(`Time Share Percentage: ${timeSharePercentage.toFixed(1)}%`, 14, finalY);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`(Based on ${totalHours.toFixed(1)} hours of ${monthlyHours} total hours in month)`, 14, finalY + 7);

        this.addFooter(doc);
        doc.save(`timeshare_report_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
    }
}
